#!/bin/sh

echo "compile-libs build system, v0.10"

while true; do
	case $1 in
		-c)
			cfgfile=$2
			shift
			;;
		-h | --help)
			echo "-c		Gives configuration file path"
			echo "-h|--help	Shows this help"
			exit 0
	esac

	if [ $# -ne 0 ]; then
		shift
	else
		break
	fi
done

if [ -f "$cfgfile" ]; then
	source "$cfgfile"
else
	if [ "$components" = "" ]; then
		echo "Error: No components listed"
		exit 1
	fi
fi

for i in $components; do
	echo "Compiling $(basename $i .$ext) component with $flags..."
	$cpl $flags -c $srcdir/$i -o obj/$i.o
done

if [ $(echo "$flags" | grep -c fPIC) -ne 0 ]; then
	echo "Linking components into $lib.so"
	$cpl -shared -o "$lib.so" obj/*.o
else
	echo "Packaging components into $lib.a..."
	ar rc "$lib.a" obj/*.o
fi
