#!/bin/sh

case $1 in
	clean)
		rm *.out *.a *.so core -f
		set +v
		;;

	build)
		cc -c -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
		ar rc libpl32.a *.o
		cc -c -fPIC -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
		cc -shared *.o -o libpl32.so
		cc --static -Iinclude tests/pl32-memory-test.c *.o -o pl32-memory-test.out -g
		cc --static -Iinclude tests/pl32-shell-test.c *.o -o pl32-shell-test.out -g
		cc --static -Iinclude tests/pl32-file-test.c *.o -o pl32-file-test.out -g
		rm *.o
		;;
esac
