#!/bin/sh

case $1 in
	clean)
		rm *.out *.a *.so core -f
		set +v
		;;

	build)
		cc -c -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
		ar rc libpl32.a *.o
		cc -c -fPIC -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
		cc -shared *.o -o libpl32.so
		cc --static -Iinclude pl32-test.c *.o -o pl32-test.out -g
		rm *.o
		;;
	install)
		cp include/* /usr/include
		mv libpl32.* /usr/lib
		;;
esac
